#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT_DIR="$ROOT_DIR/plugins/wasm-go/extensions"
OUT_DIR="$ROOT_DIR/llmstxt"
INDEX_FILE="$OUT_DIR/llms.txt"
DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"
ORIGIN_URL="${ORIGIN_URL:-$(git -C "$ROOT_DIR" remote get-url origin)}"

if [[ ! -d "$EXT_DIR" ]]; then
  echo "extensions directory not found: $EXT_DIR" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

if [[ "$ORIGIN_URL" =~ ^git@github.com:(.+)/(.+)\.git$ ]]; then
  OWNER="${BASH_REMATCH[1]}"
  REPO="${BASH_REMATCH[2]}"
elif [[ "$ORIGIN_URL" =~ ^https://github.com/(.+)/(.+)\.git$ ]]; then
  OWNER="${BASH_REMATCH[1]}"
  REPO="${BASH_REMATCH[2]}"
else
  echo "unsupported origin URL format: $ORIGIN_URL" >&2
  exit 1
fi

RAW_BASE="https://raw.githubusercontent.com/$OWNER/$REPO/$DEFAULT_BRANCH"
WEB_BASE="https://github.com/$OWNER/$REPO/blob/$DEFAULT_BRANCH"

PLUGINS=()
while IFS= read -r plugin; do
  PLUGINS+=("$plugin")
done < <(find "$EXT_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)

cat > "$INDEX_FILE" <<'HEADER'
# Higress Plugins (llms.txt Index)

> LLM-friendly index for all built-in Higress Wasm Go plugins, centralized under `/llmstxt`.

This index is generated by `llmstxt/generate-plugin-llms-txt.sh`.

## Plugin llms Files
HEADER

for plugin in "${PLUGINS[@]}"; do
  printf -- "- [%s](%s/llmstxt/%s.llms.txt): LLM-friendly plugin entry with doc/source links.\n" "$plugin" "$RAW_BASE" "$plugin" >> "$INDEX_FILE"
done

echo >> "$INDEX_FILE"
echo "## Optional" >> "$INDEX_FILE"
echo "- [Higress Plugin Hub](https://higress.cn/plugin/): Official plugin catalog and quick lookup." >> "$INDEX_FILE"
echo "- [Repository README]($RAW_BASE/README.md): Project-level overview and quick start." >> "$INDEX_FILE"

for plugin in "${PLUGINS[@]}"; do
  plugin_dir="$EXT_DIR/$plugin"
  plugin_llms="$OUT_DIR/$plugin.llms.txt"

  {
    echo "# Higress Plugin: $plugin"
    echo
    printf "> LLM-friendly entrypoint for the \`%s\` plugin in Higress.\n" "$plugin"
    echo
    echo "## Docs"
    if [[ -f "$plugin_dir/README.md" ]]; then
      echo "- [README (中文)]($RAW_BASE/plugins/wasm-go/extensions/$plugin/README.md): Main plugin documentation in Chinese."
    fi
    if [[ -f "$plugin_dir/README_EN.md" ]]; then
      echo "- [README (English)]($RAW_BASE/plugins/wasm-go/extensions/$plugin/README_EN.md): Main plugin documentation in English."
    fi

    echo
    echo "## Source"
    if [[ -f "$plugin_dir/main.go" ]]; then
      echo "- [main.go]($RAW_BASE/plugins/wasm-go/extensions/$plugin/main.go): Plugin runtime behavior and request/response processing logic."
    fi
    if [[ -f "$plugin_dir/plugin.yaml" ]]; then
      echo "- [plugin.yaml]($RAW_BASE/plugins/wasm-go/extensions/$plugin/plugin.yaml): Plugin metadata and schema information."
    fi
    if [[ -d "$plugin_dir/config" ]]; then
      echo "- [config/]($WEB_BASE/plugins/wasm-go/extensions/$plugin/config): Configuration parsing and validation logic."
    fi
    if [[ -d "$plugin_dir/testdata" ]]; then
      echo "- [testdata/]($WEB_BASE/plugins/wasm-go/extensions/$plugin/testdata): Test fixtures and sample payloads."
    fi
  } > "$plugin_llms"
done

echo "Generated index: $INDEX_FILE"
echo "Generated per-plugin llms files under: $OUT_DIR/*.llms.txt"
